import { existsSync, readFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, isAbsolute, join, relative, resolve } from 'node:path'
import { renderShell, SECURITY_HEADERS, SHELL_FILE } from '@easy-cms/admin'
import {
  CONFIG_FILE_NAMES,
  type Config,
  DEFAULT_ADMIN_PATH,
  DEFAULT_API_PATH,
  importConfig,
} from '@easy-cms/core'
import {
  addServerHandler,
  addServerImports,
  addServerPlugin,
  addTypeTemplate,
  createResolver,
  defineNuxtModule,
  useLogger,
} from '@nuxt/kit'
import type { NuxtModule } from '@nuxt/schema'

export interface ModuleOptions {
  /** Path to the Easy CMS config, relative to the project root. Default: `easy-cms.config.ts` (or .mts/.js/.mjs). */
  configPath?: string
  /** Where the REST API is served. Default `/api/cms`. */
  apiPath?: string
  /** Use `X-Forwarded-For` for the client IP (login rate limiting). Only enable behind a proxy you control. */
  trustProxy?: boolean
}

/** Nitro options this module touches. Nitro's own type augmentation is not loaded here. */
interface NitroOptions {
  virtual?: Record<string, string | (() => string)>
  externals?: { inline?: string[]; traceInclude?: string[] }
  publicAssets?: { dir: string; baseURL?: string; maxAge?: number; fallthrough?: boolean }[]
}

const SERVER = '#easy-cms-local-api'
const HANDLER = '#easy-cms-rest-handler'
const ADMIN_SHELL = '#easy-cms-admin-shell'

const module: NuxtModule<ModuleOptions> = defineNuxtModule<ModuleOptions>({
  meta: {
    name: '@easy-cms/nuxt',
    configKey: 'easyCms',
    compatibility: { nuxt: '>=4.0.0' },
  },
  defaults: {
    apiPath: DEFAULT_API_PATH,
    trustProxy: false,
  },
  async setup(options, nuxt) {
    const logger = useLogger('easy-cms')
    const { resolve: resolveRuntime } = createResolver(import.meta.url)
    const rootDir = nuxt.options.rootDir

    const configPath = options.configPath
      ? isAbsolute(options.configPath)
        ? options.configPath
        : resolve(rootDir, options.configPath)
      : CONFIG_FILE_NAMES.map((name) => join(rootDir, name)).find((path) => existsSync(path))
    if (!configPath || !existsSync(configPath)) {
      logger.warn(
        `No Easy CMS config found in ${rootDir}. Create easy-cms.config.ts (or run \`npx create-easy-cms\`). The module is disabled.`,
      )
      return
    }

    // The raw config (not validated: env vars may be missing at build time) provides
    // admin settings and bundling hints.
    let rawConfig: Config | undefined
    try {
      rawConfig = await importConfig(configPath)
    } catch (error) {
      logger.warn(`Could not read ${configPath} at build time: ${(error as Error).message}`)
    }

    const apiPath = `/${(options.apiPath ?? DEFAULT_API_PATH).replace(/^\/+|\/+$/g, '')}`
    const adminPath = `/${(rawConfig?.admin?.path ?? DEFAULT_ADMIN_PATH).replace(/^\/+|\/+$/g, '')}`
    // Forward slashes: Rollup accepts them on Windows too, and backslashes would need escaping.
    const slash = (path: string) => path.replace(/\\/g, '/')
    const runtime = (file: string) => JSON.stringify(slash(resolveRuntime(`./runtime/${file}`)))
    const config = JSON.stringify(slash(configPath))
    const nitro = (nuxt.options as unknown as { nitro: NitroOptions }).nitro

    // Virtual modules are always bundled by Nitro, so the user's TypeScript config is compiled
    // with the server in both dev and production.
    nitro.virtual ??= {}
    Object.assign(nitro.virtual, {
      [SERVER]: `import config from ${config}
import { getEasyCMS, getEasyCMSUser } from ${runtime('cms.js')}
export function useEasyCMS() { return getEasyCMS(config) }
export function useEasyCMSUser(event) { return getEasyCMSUser(config, event) }
`,
      [HANDLER]: `import config from ${config}
import { createHandler } from ${runtime('handler.js')}
export default createHandler(config, ${JSON.stringify({ basePath: apiPath, trustProxy: options.trustProxy ?? false })})
`,
    })

    // Types for the virtual module; the config is imported as a type so its literal
    // collection types flow into useEasyCMS().
    addTypeTemplate(
      {
        filename: 'types/easy-cms.d.ts',
        getContents: ({ nuxt: n }) => {
          const from = relative(join(n.options.buildDir, 'types'), configPath)
            .replace(/\\/g, '/')
            .replace(/\.(m?ts|m?js)$/, '')
          // No top-level import/export: this must stay a script so the block declares the module.
          return `// Generated by @easy-cms/nuxt
declare module '${SERVER}' {
  import type { AuthUser, EasyCMS } from '@easy-cms/core'
  import type { H3Event } from 'h3'
  type Config = typeof import('${from.startsWith('.') ? from : `./${from}`}').default

  /** The Easy CMS Local API for this server. */
  export function useEasyCMS(): Promise<EasyCMS<Config>>
  /** The logged-in Easy CMS user for this request (session cookie or Bearer token), or null. */
  export function useEasyCMSUser(event: H3Event): Promise<AuthUser | null>
}
`
        },
      },
      { nitro: true, nuxt: false },
    )

    addServerImports([
      { name: 'useEasyCMS', from: SERVER },
      { name: 'useEasyCMSUser', from: SERVER },
    ])
    addServerHandler({ route: apiPath, handler: HANDLER })
    addServerHandler({ route: `${apiPath}/**`, handler: HANDLER })
    addServerPlugin(resolveRuntime('./runtime/plugin.js'))

    // The runtime imports the virtual modules, so Nitro must bundle it rather than load it from node_modules.
    const runtimeDir = resolveRuntime('./runtime')
    nitro.externals = {
      ...nitro.externals,
      inline: [...(nitro.externals?.inline ?? []), runtimeDir],
    }

    // Admin UI: assets as Nitro public assets (CDN-friendly), the HTML shell from a handler
    // that adds security headers and the settings the app reads at startup.
    const adminPackage = createRequire(import.meta.url).resolve('@easy-cms/admin/package.json')
    const adminAppDir = join(dirname(adminPackage), 'dist/app')
    const shell = renderShell(readFileSync(join(adminAppDir, SHELL_FILE), 'utf8'), {
      basePath: adminPath,
      apiPath,
      locale: rawConfig?.admin?.locale ?? 'en',
    })
    nitro.virtual[ADMIN_SHELL] = `export const basePath = ${JSON.stringify(adminPath)}
export const html = ${JSON.stringify(shell)}
export const headers = ${JSON.stringify(SECURITY_HEADERS)}
`
    nitro.publicAssets = [
      ...(nitro.publicAssets ?? []),
      // fallthrough: app routes (not files) continue to the shell handler below.
      { dir: adminAppDir, baseURL: adminPath, maxAge: 60 * 60 * 24 * 365, fallthrough: true },
    ]
    const adminHandler = resolveRuntime('./runtime/admin.js')
    addServerHandler({ route: adminPath, handler: adminHandler })
    addServerHandler({ route: `${adminPath}/**`, handler: adminHandler })

    // Ship files the database adapter loads dynamically (e.g. libsql's native binary),
    // which Nitro's output tracing cannot find on its own.
    const traceInclude = rawConfig?.db?.bundle?.traceInclude ?? []
    if (traceInclude.length > 0) {
      const externals = nitro.externals ?? {}
      nitro.externals = {
        ...externals,
        traceInclude: [...(externals.traceInclude ?? []), ...traceInclude],
      }
    }

    // The database file changes at runtime; don't restart the dev server for it.
    nuxt.options.ignore.push('**/*.db', '**/*.db-*', 'easy-cms/migrations/**')
    nuxt.options.watch.push(configPath)

    logger.info(`Easy CMS admin at ${adminPath}, API at ${apiPath}`)
  },
})

export default module
