import { mkdir, readFile, rm, stat, writeFile } from 'node:fs/promises'
import { dirname, isAbsolute, join, normalize, resolve, sep } from 'node:path'

export interface StoredFile {
  readonly body: Uint8Array
  readonly size: number
}

/** Where uploaded files live. Keys are generated by Easy CMS: `<name>-<random>.<ext>`. */
export interface StorageAdapter {
  readonly name: string
  /** Called once with the project root, before any other method. */
  init?(args: { cwd: string }): void | Promise<void>
  put(key: string, data: Uint8Array, options: { contentType: string }): Promise<void>
  get(key: string): Promise<StoredFile | null>
  delete(key: string): Promise<void>
  /**
   * Public URL of a file, or `undefined` to serve it through the REST API
   * (`<api>/media/file/<key>`), as the local adapter does.
   */
  url?(key: string): string | undefined
}

export interface LocalStorageOptions {
  /** Directory, relative to the project root. Default `uploads`. */
  readonly dir?: string
}

/** Stores files on the local disk. Suitable for servers with a persistent filesystem. */
export function localStorage(options: LocalStorageOptions = {}): StorageAdapter {
  // turbopackIgnore: paths are only known at runtime; without it Next traces the whole project.
  let root = resolve(/* turbopackIgnore: true */ options.dir ?? 'uploads')
  const pathOf = (key: string) => {
    const path = normalize(join(/* turbopackIgnore: true */ root, key))
    if (!path.startsWith(root + sep)) throw new Error(`Invalid storage key "${key}"`)
    return path
  }
  return {
    name: 'local',
    init({ cwd }) {
      const dir = options.dir ?? 'uploads'
      root = isAbsolute(dir) ? dir : resolve(/* turbopackIgnore: true */ cwd, dir)
    },
    async put(key, data) {
      const path = pathOf(key)
      await mkdir(dirname(path), { recursive: true })
      await writeFile(path, data, { flag: 'wx' })
    },
    async get(key) {
      const path = pathOf(key)
      const info = await stat(path).catch(() => undefined)
      if (!info?.isFile()) return null
      return { body: new Uint8Array(await readFile(path)), size: info.size }
    },
    async delete(key) {
      await rm(pathOf(key), { force: true })
    },
  }
}
